language: ruby
before_install: 
  - gem install ceedling
install:
    - mkdir build
    - bundler install
script:
    - bundler exec rake 
    - bundler exec rake test:all
    - bundler exec rake gcov:all
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fb97aeee69dc0a0896fb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
